language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: identixone
  password:
    secure: LrnFCnMQSrFD0dBbtxHu1pbqdxyZyZ4doqSENKZkiWm0QO9ZINzoy80YnY5UGQiNIacSUO6+obvzKyRU5cNZiimFw2T6DTsy2maJXtQiHQPCcLthROFV8XVoUFPM2Tg/FUPsCd5XYYGZhV5F5/Oaryh9ZLlB0UAPPjpMqtUhObpYuX1MrU1dR9wb3b3PFJRuk+5tidsBAKgJXbZ8EE4XmuNCA56ZOxzLBrWwoCV/jTKUdDCxRLc4RxrNnXgf0poJBZw2hNnImmRO4Op5GK1NHM/3pSsP6oy9n0N4pyflNT6A5cg2VaWloX0Bw6TRjrxP72vj22H+ICBornHN1ZCoPKsdWlsk9Yh8NjpNldUCaJcCq+kqbFcZt+UzbR03JC57y1r/xxTBaT8RJiUNfo1IxmbeZgG7Onzu/iESkpa5GVSrnpm0OL/hyOzJecmR58MKx/frYxpulxkZ1ZRnGrrMBxdLmAwxecULZsvrR5WfFkbxYxZFqpJgiiCwisX0QEiH62gwxr2+T4MUWN3e1W+cKpLVZ6ak42FO9oEbDxV4hLPqRt9BvYyl/8OHsvm4iQrujo69TIeqhWh2Cgx7rECV9WdH5habn2CHCvDHeAg+1zUL0VnC4kU/m7+BkucG4Ksh83XLltk+WZpAifZwji215BmvJBdxPkjWG3rqHwPSlNw=
  on:
    tags: true
    repo: identixone/fastapi_contrib
    python: 3.6
